app = "nombre-del-bot" # Cambia esto por el nombre único de tu aplicación en Fly.io

[build]
builder = "paketobuildpacks/builder:base"

[env]
PORT = "8080"

[[services]]
internal_port = 8080
protocol = "tcp"

  [[services.ports]]
  handlers = ["http"]
  port = 80
